skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
agent_guard = "7HGd3guukPCe4atyc72Z4Uy7hs6r5KzbUFsmxxRTHC9W"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
